name: Deploy to GitHub Pages

on:
  workflow_call:
    inputs:
      build:
        type: string
        default: ''

      production-files:
        type: string
        default: ''

      release-branch:
        type: string
        default: main

      fetch-depth:
        type: boolean
        default: false

      environment:
        type: string
        default: github-pages

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Setup environment
        uses: tzuyi0817/workflows/setup-environment@v1
        with:
          fetch-depth: ${{ inputs.fetch-depth }}

      - name: Setup pages
        uses: actions/configure-pages@v5

      - name: Build
        run: ${{ inputs.build }}
        if: ${{ inputs.build }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        if: ${{ inputs.production-files }}
        with:
          path: ${{ inputs.production-files }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == format('refs/heads/{0}', inputs.release-branch) }}

    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v5
