name: Test

on:
  workflow_call:
    inputs:
      test:
        type: string
        default: echo skip test

      install-other-deps:
        type: string
        default: ''

      env-list:
        description: Enter one variable per line (for example, VAR=1, press Enter, then enter VAR=2).
        type: string
        default: ''

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: setup environment
        uses: tzuyi0817/workflows/setup-environment@v1

      - name: install other dependencies
        run: ${{ inputs.install-other-deps }}
        if: ${{ inputs.install-other-deps }}

      - name: setting env variables
        shell: bash
        run: |
          echo "${{ inputs.env-list }}" >> $GITHUB_ENV
        if: ${{ inputs.env-list }}

      - name: run tests
        run: ${{ inputs.test }}
